filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false


filebeat.inputs:
- type: container
  paths:
   - '/var/lib/docker/containers/*/*.log'

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - move_fields:
      from: "container.labels"
      fields: ["gw_instance"]
      to: ""
      ignore_missing: true
      when:
        has_fields: ['container.labels']

  - drop_event.when.contains.container.image.name: kibana
  - drop_event.when.contains.container.image.name: elasticsearch
  - drop_event.when.contains.container.image.name: filebeat
  - drop_event.when.contains.container.image.name: logstash


setup.template.name: "filebeat-docker"
setup.template.pattern: "filebeat-docker"


output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  index: filebeat-docker
